#pragma once

#include <hal_gpio.h>

// SAMV71 has 4 pin functions

#define GPIO_PIN_FUNCTION_A 0
#define GPIO_PIN_FUNCTION_B 1
#define GPIO_PIN_FUNCTION_C 2
#define GPIO_PIN_FUNCTION_D 3

#define PA3 GPIO(GPIO_PORTA, 3)
#define PA4 GPIO(GPIO_PORTA, 4)
#define PA5 GPIO(GPIO_PORTA, 5)
#define PA6 GPIO(GPIO_PORTA, 6)
#define PA9 GPIO(GPIO_PORTA, 9)
#define PA10 GPIO(GPIO_PORTA, 10)
#define PA21 GPIO(GPIO_PORTA, 21)
#define Yeast_Off GPIO(GPIO_PORTC, 15)
#define Trans_Irq GPIO(GPIO_PORTC, 22)
#define PB4 GPIO(GPIO_PORTB, 4)
#define PD20 GPIO(GPIO_PORTD, 20)
#define PD21 GPIO(GPIO_PORTD, 21)
#define PD22 GPIO(GPIO_PORTD, 22)
#define PD25 GPIO(GPIO_PORTD, 25)
#define PD26 GPIO(GPIO_PORTD, 26)
#define PD27 GPIO(GPIO_PORTD, 27)
#define PD28 GPIO(GPIO_PORTD, 28)

#define LED0 GPIO(GPIO_PORTA, 23)