manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: scsd-cdh
      url-base: https://github.com/scsd-cdh
  projects:
    - name: zephyr
      remote: scsd-cdh
      revision: v4.3.0-patch2
      import: true
    - name: libcsp
      remote: scsd-cdh
      revision: v2.1.1
      path: modules/lib/libcsp
  self:
    path: application
