#ifndef GENERATED_ASN1SCC__systems_H
#define GENERATED_ASN1SCC__systems_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif



extern const asn1SccSint groundSystemId;
extern const asn1SccSint cdhSystemId;
extern const asn1SccSint bmsSystemId;

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
