/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"

#include "_systems.h"

const asn1SccSint groundSystemId = 0LL;
const asn1SccSint cdhSystemId = 1LL;
const asn1SccSint bmsSystemId = 2LL;

