#ifndef GENERATED_ASN1SCC_bms_H
#define GENERATED_ASN1SCC_bms_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef uint16_t BMSADCValue;


#define ERR_BMSADCVALUE		1  /*(0..65535)*/
flag BMSADCValue_IsConstraintValid(const BMSADCValue* pVal, int* pErrCode);

void BMSADCValue_Initialize(BMSADCValue* pVal);

#define ERR_UPER_ENCODE_BMSADCVALUE		2  /**/
#define BMSADCValue_REQUIRED_BYTES_FOR_ENCODING       2
#define BMSADCValue_REQUIRED_BITS_FOR_ENCODING        16

flag BMSADCValue_Encode(const BMSADCValue* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BMSADCVALUE		3  /**/
flag BMSADCValue_Decode(BMSADCValue* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- BMSCellStatus --------------------------------------------*/
typedef struct {
    flag overvoltage;
    flag undervoltage;
    BMSADCValue voltage;

} BMSCellStatus;

#define ERR_BMSCELLSTATUS		26  /**/
#define ERR_BMSCELLSTATUS_OVERVOLTAGE		6  /**/
#define ERR_BMSCELLSTATUS_UNDERVOLTAGE		11  /**/
#define ERR_BMSCELLSTATUS_VOLTAGE_2		21  /**/
flag BMSCellStatus_IsConstraintValid(const BMSCellStatus* pVal, int* pErrCode);

void BMSCellStatus_Initialize(BMSCellStatus* pVal);

#define ERR_UPER_ENCODE_BMSCELLSTATUS		27  /**/
#define ERR_UPER_ENCODE_BMSCELLSTATUS_OVERVOLTAGE		7  /**/
#define ERR_UPER_ENCODE_BMSCELLSTATUS_UNDERVOLTAGE		12  /**/
#define ERR_UPER_ENCODE_BMSCELLSTATUS_VOLTAGE_2		22  /**/
#define BMSCellStatus_REQUIRED_BYTES_FOR_ENCODING       3
#define BMSCellStatus_REQUIRED_BITS_FOR_ENCODING        18

flag BMSCellStatus_Encode(const BMSCellStatus* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BMSCELLSTATUS		28  /**/
#define ERR_UPER_DECODE_BMSCELLSTATUS_OVERVOLTAGE		8  /**/
#define ERR_UPER_DECODE_BMSCELLSTATUS_UNDERVOLTAGE		13  /**/
#define ERR_UPER_DECODE_BMSCELLSTATUS_VOLTAGE_2		23  /**/
flag BMSCellStatus_Decode(BMSCellStatus* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- BMSBatteryPackStatus --------------------------------------------*/
typedef struct {
    BMSCellStatus cellA;
    BMSCellStatus cellB;
    BMSADCValue currentDraw;
    BMSADCValue currentCharge;
    BMSADCValue voltage;
    flag overcurrent;

} BMSBatteryPackStatus;

#define ERR_BMSBATTERYPACKSTATUS		76  /**/
#define ERR_BMSBATTERYPACKSTATUS_CELLA		31  /**/
#define ERR_BMSBATTERYPACKSTATUS_CELLB		36  /**/
#define ERR_BMSBATTERYPACKSTATUS_CURRENTDRAW_2		46  /**/
#define ERR_BMSBATTERYPACKSTATUS_CURRENTCHARGE_2		56  /**/
#define ERR_BMSBATTERYPACKSTATUS_VOLTAGE_2		66  /**/
#define ERR_BMSBATTERYPACKSTATUS_OVERCURRENT		71  /**/
flag BMSBatteryPackStatus_IsConstraintValid(const BMSBatteryPackStatus* pVal, int* pErrCode);

void BMSBatteryPackStatus_Initialize(BMSBatteryPackStatus* pVal);

#define ERR_UPER_ENCODE_BMSBATTERYPACKSTATUS		77  /**/
#define ERR_UPER_ENCODE_BMSBATTERYPACKSTATUS_CELLA		32  /**/
#define ERR_UPER_ENCODE_BMSBATTERYPACKSTATUS_CELLB		37  /**/
#define ERR_UPER_ENCODE_BMSBATTERYPACKSTATUS_CURRENTDRAW_2		47  /**/
#define ERR_UPER_ENCODE_BMSBATTERYPACKSTATUS_CURRENTCHARGE_2		57  /**/
#define ERR_UPER_ENCODE_BMSBATTERYPACKSTATUS_VOLTAGE_2		67  /**/
#define ERR_UPER_ENCODE_BMSBATTERYPACKSTATUS_OVERCURRENT		72  /**/
#define BMSBatteryPackStatus_REQUIRED_BYTES_FOR_ENCODING       11
#define BMSBatteryPackStatus_REQUIRED_BITS_FOR_ENCODING        85

flag BMSBatteryPackStatus_Encode(const BMSBatteryPackStatus* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BMSBATTERYPACKSTATUS		78  /**/
#define ERR_UPER_DECODE_BMSBATTERYPACKSTATUS_CELLA		33  /**/
#define ERR_UPER_DECODE_BMSBATTERYPACKSTATUS_CELLB		38  /**/
#define ERR_UPER_DECODE_BMSBATTERYPACKSTATUS_CURRENTDRAW_2		48  /**/
#define ERR_UPER_DECODE_BMSBATTERYPACKSTATUS_CURRENTCHARGE_2		58  /**/
#define ERR_UPER_DECODE_BMSBATTERYPACKSTATUS_VOLTAGE_2		68  /**/
#define ERR_UPER_DECODE_BMSBATTERYPACKSTATUS_OVERCURRENT		73  /**/
flag BMSBatteryPackStatus_Decode(BMSBatteryPackStatus* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- BMSPowerStatusResponse --------------------------------------------*/
typedef struct {
    BMSBatteryPackStatus batteryPack1;
    BMSBatteryPackStatus batteryPack2;

} BMSPowerStatusResponse;

#define ERR_BMSPOWERSTATUSRESPONSE		91  /**/
#define ERR_BMSPOWERSTATUSRESPONSE_BATTERYPACK1		81  /**/
#define ERR_BMSPOWERSTATUSRESPONSE_BATTERYPACK2		86  /**/
flag BMSPowerStatusResponse_IsConstraintValid(const BMSPowerStatusResponse* pVal, int* pErrCode);

void BMSPowerStatusResponse_Initialize(BMSPowerStatusResponse* pVal);

#define ERR_UPER_ENCODE_BMSPOWERSTATUSRESPONSE		92  /**/
#define ERR_UPER_ENCODE_BMSPOWERSTATUSRESPONSE_BATTERYPACK1		82  /**/
#define ERR_UPER_ENCODE_BMSPOWERSTATUSRESPONSE_BATTERYPACK2		87  /**/
#define BMSPowerStatusResponse_REQUIRED_BYTES_FOR_ENCODING       22
#define BMSPowerStatusResponse_REQUIRED_BITS_FOR_ENCODING        170

flag BMSPowerStatusResponse_Encode(const BMSPowerStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BMSPOWERSTATUSRESPONSE		93  /**/
#define ERR_UPER_DECODE_BMSPOWERSTATUSRESPONSE_BATTERYPACK1		83  /**/
#define ERR_UPER_DECODE_BMSPOWERSTATUSRESPONSE_BATTERYPACK2		88  /**/
flag BMSPowerStatusResponse_Decode(BMSPowerStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- BMSTemperatureStatusResponse --------------------------------------------*/


typedef struct {
    BMSADCValue arr[8];
} BMSTemperatureStatusResponse_thermistors;
typedef struct {
    BMSTemperatureStatusResponse_thermistors thermistors;

} BMSTemperatureStatusResponse;

#define ERR_BMSTEMPERATURESTATUSRESPONSE_THERMISTORS		106  /*SIZE(8)*/
#define ERR_BMSTEMPERATURESTATUSRESPONSE_THERMISTORS_ELM_2		101  /**/
flag BMSTemperatureStatusResponse_thermistors_IsConstraintValid(const BMSTemperatureStatusResponse_thermistors* pVal, int* pErrCode);

#define ERR_BMSTEMPERATURESTATUSRESPONSE		111  /**/
flag BMSTemperatureStatusResponse_IsConstraintValid(const BMSTemperatureStatusResponse* pVal, int* pErrCode);

void BMSTemperatureStatusResponse_thermistors_Initialize(BMSTemperatureStatusResponse_thermistors* pVal);
void BMSTemperatureStatusResponse_Initialize(BMSTemperatureStatusResponse* pVal);

#define ERR_UPER_ENCODE_BMSTEMPERATURESTATUSRESPONSE		112  /**/
#define ERR_UPER_ENCODE_BMSTEMPERATURESTATUSRESPONSE_THERMISTORS		107  /**/
#define ERR_UPER_ENCODE_BMSTEMPERATURESTATUSRESPONSE_THERMISTORS_ELM_2		102  /**/
#define BMSTemperatureStatusResponse_REQUIRED_BYTES_FOR_ENCODING       16
#define BMSTemperatureStatusResponse_REQUIRED_BITS_FOR_ENCODING        128

flag BMSTemperatureStatusResponse_Encode(const BMSTemperatureStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BMSTEMPERATURESTATUSRESPONSE		113  /**/
#define ERR_UPER_DECODE_BMSTEMPERATURESTATUSRESPONSE_THERMISTORS		108  /**/
#define ERR_UPER_DECODE_BMSTEMPERATURESTATUSRESPONSE_THERMISTORS_ELM_2		103  /**/
flag BMSTemperatureStatusResponse_Decode(BMSTemperatureStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- BMSSystemStatusRequest --------------------------------------------*/
typedef uint8_t BMSSystemStatusRequest_placeholder;

typedef struct {
    BMSSystemStatusRequest_placeholder placeholder;

} BMSSystemStatusRequest;

#define ERR_BMSSYSTEMSTATUSREQUEST_PLACEHOLDER		116  /*(0)*/
flag BMSSystemStatusRequest_placeholder_IsConstraintValid(const BMSSystemStatusRequest_placeholder* pVal, int* pErrCode);

#define ERR_BMSSYSTEMSTATUSREQUEST		121  /**/
flag BMSSystemStatusRequest_IsConstraintValid(const BMSSystemStatusRequest* pVal, int* pErrCode);

void BMSSystemStatusRequest_placeholder_Initialize(BMSSystemStatusRequest_placeholder* pVal);
void BMSSystemStatusRequest_Initialize(BMSSystemStatusRequest* pVal);

#define ERR_UPER_ENCODE_BMSSYSTEMSTATUSREQUEST		122  /**/
#define ERR_UPER_ENCODE_BMSSYSTEMSTATUSREQUEST_PLACEHOLDER		117  /**/
#define BMSSystemStatusRequest_REQUIRED_BYTES_FOR_ENCODING       0
#define BMSSystemStatusRequest_REQUIRED_BITS_FOR_ENCODING        0

flag BMSSystemStatusRequest_Encode(const BMSSystemStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BMSSYSTEMSTATUSREQUEST		123  /**/
#define ERR_UPER_DECODE_BMSSYSTEMSTATUSREQUEST_PLACEHOLDER		118  /**/
flag BMSSystemStatusRequest_Decode(BMSSystemStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- BMSSystemStatusResponse --------------------------------------------*/
typedef uint8_t BMSSystemStatusResponse_version;

typedef uint32_t BMSSystemStatusResponse_uptime;

typedef struct {
    BMSSystemStatusResponse_version version;
    BMSSystemStatusResponse_uptime uptime;

} BMSSystemStatusResponse;

#define ERR_BMSSYSTEMSTATUSRESPONSE_VERSION		126  /*(0..255)*/
flag BMSSystemStatusResponse_version_IsConstraintValid(const BMSSystemStatusResponse_version* pVal, int* pErrCode);

#define ERR_BMSSYSTEMSTATUSRESPONSE_UPTIME		131  /*(0..4294967295)*/
flag BMSSystemStatusResponse_uptime_IsConstraintValid(const BMSSystemStatusResponse_uptime* pVal, int* pErrCode);

#define ERR_BMSSYSTEMSTATUSRESPONSE		136  /**/
flag BMSSystemStatusResponse_IsConstraintValid(const BMSSystemStatusResponse* pVal, int* pErrCode);

void BMSSystemStatusResponse_version_Initialize(BMSSystemStatusResponse_version* pVal);
void BMSSystemStatusResponse_uptime_Initialize(BMSSystemStatusResponse_uptime* pVal);
void BMSSystemStatusResponse_Initialize(BMSSystemStatusResponse* pVal);

#define ERR_UPER_ENCODE_BMSSYSTEMSTATUSRESPONSE		137  /**/
#define ERR_UPER_ENCODE_BMSSYSTEMSTATUSRESPONSE_VERSION		127  /**/
#define ERR_UPER_ENCODE_BMSSYSTEMSTATUSRESPONSE_UPTIME		132  /**/
#define BMSSystemStatusResponse_REQUIRED_BYTES_FOR_ENCODING       5
#define BMSSystemStatusResponse_REQUIRED_BITS_FOR_ENCODING        40

flag BMSSystemStatusResponse_Encode(const BMSSystemStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BMSSYSTEMSTATUSRESPONSE		138  /**/
#define ERR_UPER_DECODE_BMSSYSTEMSTATUSRESPONSE_VERSION		128  /**/
#define ERR_UPER_DECODE_BMSSYSTEMSTATUSRESPONSE_UPTIME		133  /**/
flag BMSSystemStatusResponse_Decode(BMSSystemStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- BMSPowerStatusRequest --------------------------------------------*/
typedef uint8_t BMSPowerStatusRequest_placeholder;

typedef struct {
    BMSPowerStatusRequest_placeholder placeholder;

} BMSPowerStatusRequest;

#define ERR_BMSPOWERSTATUSREQUEST_PLACEHOLDER		141  /*(0)*/
flag BMSPowerStatusRequest_placeholder_IsConstraintValid(const BMSPowerStatusRequest_placeholder* pVal, int* pErrCode);

#define ERR_BMSPOWERSTATUSREQUEST		146  /**/
flag BMSPowerStatusRequest_IsConstraintValid(const BMSPowerStatusRequest* pVal, int* pErrCode);

void BMSPowerStatusRequest_placeholder_Initialize(BMSPowerStatusRequest_placeholder* pVal);
void BMSPowerStatusRequest_Initialize(BMSPowerStatusRequest* pVal);

#define ERR_UPER_ENCODE_BMSPOWERSTATUSREQUEST		147  /**/
#define ERR_UPER_ENCODE_BMSPOWERSTATUSREQUEST_PLACEHOLDER		142  /**/
#define BMSPowerStatusRequest_REQUIRED_BYTES_FOR_ENCODING       0
#define BMSPowerStatusRequest_REQUIRED_BITS_FOR_ENCODING        0

flag BMSPowerStatusRequest_Encode(const BMSPowerStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BMSPOWERSTATUSREQUEST		148  /**/
#define ERR_UPER_DECODE_BMSPOWERSTATUSREQUEST_PLACEHOLDER		143  /**/
flag BMSPowerStatusRequest_Decode(BMSPowerStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- BMSSetHeaterDutyRequest --------------------------------------------*/
typedef uint8_t BMSSetHeaterDutyRequest_heater1;

typedef uint8_t BMSSetHeaterDutyRequest_heater2;

typedef uint8_t BMSSetHeaterDutyRequest_heater3;

typedef uint8_t BMSSetHeaterDutyRequest_heater4;

typedef struct {
    unsigned long heater1:1;
    unsigned long heater2:1;
    unsigned long heater3:1;
    unsigned long heater4:1;
} BMSSetHeaterDutyRequest_exist;
typedef struct {
    BMSSetHeaterDutyRequest_heater1 heater1;
    BMSSetHeaterDutyRequest_heater2 heater2;
    BMSSetHeaterDutyRequest_heater3 heater3;
    BMSSetHeaterDutyRequest_heater4 heater4;

    BMSSetHeaterDutyRequest_exist exist;

} BMSSetHeaterDutyRequest;

#define ERR_BMSSETHEATERDUTYREQUEST_HEATER1		151  /*(0..99)*/
flag BMSSetHeaterDutyRequest_heater1_IsConstraintValid(const BMSSetHeaterDutyRequest_heater1* pVal, int* pErrCode);

#define ERR_BMSSETHEATERDUTYREQUEST_HEATER2		156  /*(0..99)*/
flag BMSSetHeaterDutyRequest_heater2_IsConstraintValid(const BMSSetHeaterDutyRequest_heater2* pVal, int* pErrCode);

#define ERR_BMSSETHEATERDUTYREQUEST_HEATER3		161  /*(0..99)*/
flag BMSSetHeaterDutyRequest_heater3_IsConstraintValid(const BMSSetHeaterDutyRequest_heater3* pVal, int* pErrCode);

#define ERR_BMSSETHEATERDUTYREQUEST_HEATER4		166  /*(0..99)*/
flag BMSSetHeaterDutyRequest_heater4_IsConstraintValid(const BMSSetHeaterDutyRequest_heater4* pVal, int* pErrCode);

#define ERR_BMSSETHEATERDUTYREQUEST		171  /**/
flag BMSSetHeaterDutyRequest_IsConstraintValid(const BMSSetHeaterDutyRequest* pVal, int* pErrCode);

void BMSSetHeaterDutyRequest_heater1_Initialize(BMSSetHeaterDutyRequest_heater1* pVal);
void BMSSetHeaterDutyRequest_heater2_Initialize(BMSSetHeaterDutyRequest_heater2* pVal);
void BMSSetHeaterDutyRequest_heater3_Initialize(BMSSetHeaterDutyRequest_heater3* pVal);
void BMSSetHeaterDutyRequest_heater4_Initialize(BMSSetHeaterDutyRequest_heater4* pVal);
void BMSSetHeaterDutyRequest_Initialize(BMSSetHeaterDutyRequest* pVal);

#define ERR_UPER_ENCODE_BMSSETHEATERDUTYREQUEST		172  /**/
#define ERR_UPER_ENCODE_BMSSETHEATERDUTYREQUEST_HEATER1		152  /**/
#define ERR_UPER_ENCODE_BMSSETHEATERDUTYREQUEST_HEATER2		157  /**/
#define ERR_UPER_ENCODE_BMSSETHEATERDUTYREQUEST_HEATER3		162  /**/
#define ERR_UPER_ENCODE_BMSSETHEATERDUTYREQUEST_HEATER4		167  /**/
#define BMSSetHeaterDutyRequest_REQUIRED_BYTES_FOR_ENCODING       4
#define BMSSetHeaterDutyRequest_REQUIRED_BITS_FOR_ENCODING        32

flag BMSSetHeaterDutyRequest_Encode(const BMSSetHeaterDutyRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST		173  /**/
#define ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST_HEATER1		153  /**/
#define ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST_HEATER2		158  /**/
#define ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST_HEATER3		163  /**/
#define ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST_HEATER4		168  /**/
flag BMSSetHeaterDutyRequest_Decode(BMSSetHeaterDutyRequest* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- BMSSetHeaterDutyResponse --------------------------------------------*/
typedef uint8_t BMSSetHeaterDutyResponse_placeholder;

typedef struct {
    BMSSetHeaterDutyResponse_placeholder placeholder;

} BMSSetHeaterDutyResponse;

#define ERR_BMSSETHEATERDUTYRESPONSE_PLACEHOLDER		176  /*(0)*/
flag BMSSetHeaterDutyResponse_placeholder_IsConstraintValid(const BMSSetHeaterDutyResponse_placeholder* pVal, int* pErrCode);

#define ERR_BMSSETHEATERDUTYRESPONSE		181  /**/
flag BMSSetHeaterDutyResponse_IsConstraintValid(const BMSSetHeaterDutyResponse* pVal, int* pErrCode);

void BMSSetHeaterDutyResponse_placeholder_Initialize(BMSSetHeaterDutyResponse_placeholder* pVal);
void BMSSetHeaterDutyResponse_Initialize(BMSSetHeaterDutyResponse* pVal);

#define ERR_UPER_ENCODE_BMSSETHEATERDUTYRESPONSE		182  /**/
#define ERR_UPER_ENCODE_BMSSETHEATERDUTYRESPONSE_PLACEHOLDER		177  /**/
#define BMSSetHeaterDutyResponse_REQUIRED_BYTES_FOR_ENCODING       0
#define BMSSetHeaterDutyResponse_REQUIRED_BITS_FOR_ENCODING        0

flag BMSSetHeaterDutyResponse_Encode(const BMSSetHeaterDutyResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BMSSETHEATERDUTYRESPONSE		183  /**/
#define ERR_UPER_DECODE_BMSSETHEATERDUTYRESPONSE_PLACEHOLDER		178  /**/
flag BMSSetHeaterDutyResponse_Decode(BMSSetHeaterDutyResponse* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- BMSTemperatureStatusRequest --------------------------------------------*/
typedef uint8_t BMSTemperatureStatusRequest_placeholder;

typedef struct {
    BMSTemperatureStatusRequest_placeholder placeholder;

} BMSTemperatureStatusRequest;

#define ERR_BMSTEMPERATURESTATUSREQUEST_PLACEHOLDER		186  /*(0)*/
flag BMSTemperatureStatusRequest_placeholder_IsConstraintValid(const BMSTemperatureStatusRequest_placeholder* pVal, int* pErrCode);

#define ERR_BMSTEMPERATURESTATUSREQUEST		191  /**/
flag BMSTemperatureStatusRequest_IsConstraintValid(const BMSTemperatureStatusRequest* pVal, int* pErrCode);

void BMSTemperatureStatusRequest_placeholder_Initialize(BMSTemperatureStatusRequest_placeholder* pVal);
void BMSTemperatureStatusRequest_Initialize(BMSTemperatureStatusRequest* pVal);

#define ERR_UPER_ENCODE_BMSTEMPERATURESTATUSREQUEST		192  /**/
#define ERR_UPER_ENCODE_BMSTEMPERATURESTATUSREQUEST_PLACEHOLDER		187  /**/
#define BMSTemperatureStatusRequest_REQUIRED_BYTES_FOR_ENCODING       0
#define BMSTemperatureStatusRequest_REQUIRED_BITS_FOR_ENCODING        0

flag BMSTemperatureStatusRequest_Encode(const BMSTemperatureStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BMSTEMPERATURESTATUSREQUEST		193  /**/
#define ERR_UPER_DECODE_BMSTEMPERATURESTATUSREQUEST_PLACEHOLDER		188  /**/
flag BMSTemperatureStatusRequest_Decode(BMSTemperatureStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode);

extern const asn1SccSint lfpIdBMSSystemStatusRequest;
extern const asn1SccSint lfpIdBMSSystemStatusResponse;
extern const asn1SccSint lfpIdBMSPowerStatusRequest;
extern const asn1SccSint lfpIdBMSPowerStatusResponse;
extern const asn1SccSint lfpIdBMSSetHeaterDutyRequest;
extern const asn1SccSint lfpIdBMSSetHeaterDutyResponse;
extern const asn1SccSint lfpIdBMSTemperatureStatusRequest;
extern const asn1SccSint lfpIdBMSTemperatureStatusResponse;

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
