/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"

#include "bms.h"

const asn1SccSint lfpIdBMSSystemStatusRequest = 0LL;
const asn1SccSint lfpIdBMSSystemStatusResponse = 1LL;
const asn1SccSint lfpIdBMSPowerStatusRequest = 2LL;
const asn1SccSint lfpIdBMSPowerStatusResponse = 3LL;
const asn1SccSint lfpIdBMSSetHeaterDutyRequest = 4LL;
const asn1SccSint lfpIdBMSSetHeaterDutyResponse = 5LL;
const asn1SccSint lfpIdBMSTemperatureStatusRequest = 6LL;
const asn1SccSint lfpIdBMSTemperatureStatusResponse = 7LL;

flag BMSADCValue_IsConstraintValid(const BMSADCValue* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void BMSADCValue_Initialize(BMSADCValue* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}

flag BMSADCValue_Encode(const BMSADCValue* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? BMSADCValue_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (asn1SccUint)((*(pVal))), 0, 65535);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BMSADCValue_Decode(BMSADCValue* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumberUInt16(pBitStrm, pVal, 0, 65535);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSADCVALUE;

	return ret  && BMSADCValue_IsConstraintValid(pVal, pErrCode);
}


flag BMSCellStatus_IsConstraintValid(const BMSCellStatus* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = BMSADCValue_IsConstraintValid((&(pVal->voltage)), pErrCode);

	return ret;
}

void BMSCellStatus_Initialize(BMSCellStatus* pVal)
{
	(void)pVal;


	/*set overvoltage */
	pVal->overvoltage = FALSE;
	/*set undervoltage */
	pVal->undervoltage = FALSE;
	/*set voltage */
	BMSADCValue_Initialize((&(pVal->voltage)));
}

flag BMSCellStatus_Encode(const BMSCellStatus* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? BMSCellStatus_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode overvoltage */
	    BitStream_AppendBit(pBitStrm,pVal->overvoltage);
	    if (ret) {
	        /*Encode undervoltage */
	        BitStream_AppendBit(pBitStrm,pVal->undervoltage);
	        if (ret) {
	            /*Encode voltage */
	            ret = BMSADCValue_Encode((&(pVal->voltage)), pBitStrm, pErrCode, FALSE);
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BMSCellStatus_Decode(BMSCellStatus* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode overvoltage */
	ret = BitStream_ReadBit(pBitStrm, (&(pVal->overvoltage)));
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSCELLSTATUS_OVERVOLTAGE;
	if (ret) {
	    /*Decode undervoltage */
	    ret = BitStream_ReadBit(pBitStrm, (&(pVal->undervoltage)));
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSCELLSTATUS_UNDERVOLTAGE;
	    if (ret) {
	        /*Decode voltage */
	        ret = BMSADCValue_Decode((&(pVal->voltage)), pBitStrm, pErrCode);
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && BMSCellStatus_IsConstraintValid(pVal, pErrCode);
}


flag BMSBatteryPackStatus_IsConstraintValid(const BMSBatteryPackStatus* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = BMSCellStatus_IsConstraintValid((&(pVal->cellA)), pErrCode);
    if (ret) {
        ret = BMSCellStatus_IsConstraintValid((&(pVal->cellB)), pErrCode);
        if (ret) {
            ret = BMSADCValue_IsConstraintValid((&(pVal->currentDraw)), pErrCode);
            if (ret) {
                ret = BMSADCValue_IsConstraintValid((&(pVal->currentCharge)), pErrCode);
                if (ret) {
                    ret = BMSADCValue_IsConstraintValid((&(pVal->voltage)), pErrCode);
                }   /*COVERAGE_IGNORE*/
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void BMSBatteryPackStatus_Initialize(BMSBatteryPackStatus* pVal)
{
	(void)pVal;


	/*set cellA */
	BMSCellStatus_Initialize((&(pVal->cellA)));
	/*set cellB */
	BMSCellStatus_Initialize((&(pVal->cellB)));
	/*set currentDraw */
	BMSADCValue_Initialize((&(pVal->currentDraw)));
	/*set currentCharge */
	BMSADCValue_Initialize((&(pVal->currentCharge)));
	/*set voltage */
	BMSADCValue_Initialize((&(pVal->voltage)));
	/*set overcurrent */
	pVal->overcurrent = FALSE;
}

flag BMSBatteryPackStatus_Encode(const BMSBatteryPackStatus* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? BMSBatteryPackStatus_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode cellA */
	    ret = BMSCellStatus_Encode((&(pVal->cellA)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode cellB */
	        ret = BMSCellStatus_Encode((&(pVal->cellB)), pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode currentDraw */
	            ret = BMSADCValue_Encode((&(pVal->currentDraw)), pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode currentCharge */
	                ret = BMSADCValue_Encode((&(pVal->currentCharge)), pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode voltage */
	                    ret = BMSADCValue_Encode((&(pVal->voltage)), pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode overcurrent */
	                        BitStream_AppendBit(pBitStrm,pVal->overcurrent);
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BMSBatteryPackStatus_Decode(BMSBatteryPackStatus* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode cellA */
	ret = BMSCellStatus_Decode((&(pVal->cellA)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode cellB */
	    ret = BMSCellStatus_Decode((&(pVal->cellB)), pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode currentDraw */
	        ret = BMSADCValue_Decode((&(pVal->currentDraw)), pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode currentCharge */
	            ret = BMSADCValue_Decode((&(pVal->currentCharge)), pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode voltage */
	                ret = BMSADCValue_Decode((&(pVal->voltage)), pBitStrm, pErrCode);
	                if (ret) {
	                    /*Decode overcurrent */
	                    ret = BitStream_ReadBit(pBitStrm, (&(pVal->overcurrent)));
	                    *pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSBATTERYPACKSTATUS_OVERCURRENT;
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && BMSBatteryPackStatus_IsConstraintValid(pVal, pErrCode);
}


flag BMSPowerStatusResponse_IsConstraintValid(const BMSPowerStatusResponse* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = BMSBatteryPackStatus_IsConstraintValid((&(pVal->batteryPack1)), pErrCode);
    if (ret) {
        ret = BMSBatteryPackStatus_IsConstraintValid((&(pVal->batteryPack2)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void BMSPowerStatusResponse_Initialize(BMSPowerStatusResponse* pVal)
{
	(void)pVal;


	/*set batteryPack1 */
	BMSBatteryPackStatus_Initialize((&(pVal->batteryPack1)));
	/*set batteryPack2 */
	BMSBatteryPackStatus_Initialize((&(pVal->batteryPack2)));
}

flag BMSPowerStatusResponse_Encode(const BMSPowerStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? BMSPowerStatusResponse_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode batteryPack1 */
	    ret = BMSBatteryPackStatus_Encode((&(pVal->batteryPack1)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode batteryPack2 */
	        ret = BMSBatteryPackStatus_Encode((&(pVal->batteryPack2)), pBitStrm, pErrCode, FALSE);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BMSPowerStatusResponse_Decode(BMSPowerStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode batteryPack1 */
	ret = BMSBatteryPackStatus_Decode((&(pVal->batteryPack1)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode batteryPack2 */
	    ret = BMSBatteryPackStatus_Decode((&(pVal->batteryPack2)), pBitStrm, pErrCode);
	}   /*COVERAGE_IGNORE*/

	return ret  && BMSPowerStatusResponse_IsConstraintValid(pVal, pErrCode);
}


flag BMSTemperatureStatusResponse_thermistors_IsConstraintValid(const BMSTemperatureStatusResponse_thermistors* pVal, int* pErrCode)
{
    flag ret = TRUE;
    int i1;
    for(i1 = 0; ret && i1 < 8; i1++)
    {
    	ret = BMSADCValue_IsConstraintValid((&(pVal->arr[i1])), pErrCode);
    }

	return ret;
}

flag BMSTemperatureStatusResponse_IsConstraintValid(const BMSTemperatureStatusResponse* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = BMSTemperatureStatusResponse_thermistors_IsConstraintValid((&(pVal->thermistors)), pErrCode);

	return ret;
}

void BMSTemperatureStatusResponse_thermistors_Initialize(BMSTemperatureStatusResponse_thermistors* pVal)
{
	(void)pVal;

    int i1;

	i1 = 0;
	while (i1< 8) {
	    pVal->arr[i1] = 0UL;
	    i1 = i1 + 1;
	}

}
void BMSTemperatureStatusResponse_Initialize(BMSTemperatureStatusResponse* pVal)
{
	(void)pVal;


	/*set thermistors */
	BMSTemperatureStatusResponse_thermistors_Initialize((&(pVal->thermistors)));
}

flag BMSTemperatureStatusResponse_Encode(const BMSTemperatureStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	int i1;
	*pErrCode = 0;
	ret = bCheckConstraints ? BMSTemperatureStatusResponse_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode thermistors */
	    for(i1=0; (i1 < (int)8) && ret; i1++)
	    {
	    	ret = BMSADCValue_Encode((&(pVal->thermistors.arr[i1])), pBitStrm, pErrCode, FALSE);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BMSTemperatureStatusResponse_Decode(BMSTemperatureStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	int i1;

	/*Decode thermistors */
	for(i1=0; (i1 < (int)8) && ret; i1++)
	{
		ret = BMSADCValue_Decode((&(pVal->thermistors.arr[i1])), pBitStrm, pErrCode);
	}

	return ret  && BMSTemperatureStatusResponse_IsConstraintValid(pVal, pErrCode);
}


flag BMSSystemStatusRequest_placeholder_IsConstraintValid(const BMSSystemStatusRequest_placeholder* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == 0UL);
    *pErrCode = ret ? 0 :  ERR_BMSSYSTEMSTATUSREQUEST_PLACEHOLDER;

	return ret;
}

flag BMSSystemStatusRequest_IsConstraintValid(const BMSSystemStatusRequest* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = BMSSystemStatusRequest_placeholder_IsConstraintValid((&(pVal->placeholder)), pErrCode);

	return ret;
}

void BMSSystemStatusRequest_placeholder_Initialize(BMSSystemStatusRequest_placeholder* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void BMSSystemStatusRequest_Initialize(BMSSystemStatusRequest* pVal)
{
	(void)pVal;


	/*set placeholder */
	BMSSystemStatusRequest_placeholder_Initialize((&(pVal->placeholder)));
}

flag BMSSystemStatusRequest_Encode(const BMSSystemStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? BMSSystemStatusRequest_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode placeholder */
	    /* No need to encode value since it will always be 0UL */
	    (void)pBitStrm;
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BMSSystemStatusRequest_Decode(BMSSystemStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;


	/*Decode placeholder */
	pVal->placeholder=0UL;
	(void)pBitStrm;
	ret = TRUE;
	*pErrCode = 0;

	return ret  && BMSSystemStatusRequest_IsConstraintValid(pVal, pErrCode);
}


flag BMSSystemStatusResponse_version_IsConstraintValid(const BMSSystemStatusResponse_version* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

flag BMSSystemStatusResponse_uptime_IsConstraintValid(const BMSSystemStatusResponse_uptime* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

flag BMSSystemStatusResponse_IsConstraintValid(const BMSSystemStatusResponse* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = BMSSystemStatusResponse_version_IsConstraintValid((&(pVal->version)), pErrCode);
    if (ret) {
        ret = BMSSystemStatusResponse_uptime_IsConstraintValid((&(pVal->uptime)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void BMSSystemStatusResponse_version_Initialize(BMSSystemStatusResponse_version* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void BMSSystemStatusResponse_uptime_Initialize(BMSSystemStatusResponse_uptime* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void BMSSystemStatusResponse_Initialize(BMSSystemStatusResponse* pVal)
{
	(void)pVal;


	/*set version */
	BMSSystemStatusResponse_version_Initialize((&(pVal->version)));
	/*set uptime */
	BMSSystemStatusResponse_uptime_Initialize((&(pVal->uptime)));
}

flag BMSSystemStatusResponse_Encode(const BMSSystemStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? BMSSystemStatusResponse_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode version */
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (asn1SccUint)(pVal->version), 0, 255);
	    if (ret) {
	        /*Encode uptime */
	        BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (asn1SccUint)(pVal->uptime), 0, 4294967295LL);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BMSSystemStatusResponse_Decode(BMSSystemStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode version */
	ret = BitStream_DecodeConstraintPosWholeNumberUInt8(pBitStrm, (&(pVal->version)), 0, 255);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSSYSTEMSTATUSRESPONSE_VERSION;
	if (ret) {
	    /*Decode uptime */
	    ret = BitStream_DecodeConstraintPosWholeNumberUInt32(pBitStrm, (&(pVal->uptime)), 0, 4294967295LL);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSSYSTEMSTATUSRESPONSE_UPTIME;
	}   /*COVERAGE_IGNORE*/

	return ret  && BMSSystemStatusResponse_IsConstraintValid(pVal, pErrCode);
}


flag BMSPowerStatusRequest_placeholder_IsConstraintValid(const BMSPowerStatusRequest_placeholder* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == 0UL);
    *pErrCode = ret ? 0 :  ERR_BMSPOWERSTATUSREQUEST_PLACEHOLDER;

	return ret;
}

flag BMSPowerStatusRequest_IsConstraintValid(const BMSPowerStatusRequest* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = BMSPowerStatusRequest_placeholder_IsConstraintValid((&(pVal->placeholder)), pErrCode);

	return ret;
}

void BMSPowerStatusRequest_placeholder_Initialize(BMSPowerStatusRequest_placeholder* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void BMSPowerStatusRequest_Initialize(BMSPowerStatusRequest* pVal)
{
	(void)pVal;


	/*set placeholder */
	BMSPowerStatusRequest_placeholder_Initialize((&(pVal->placeholder)));
}

flag BMSPowerStatusRequest_Encode(const BMSPowerStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? BMSPowerStatusRequest_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode placeholder */
	    /* No need to encode value since it will always be 0UL */
	    (void)pBitStrm;
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BMSPowerStatusRequest_Decode(BMSPowerStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;


	/*Decode placeholder */
	pVal->placeholder=0UL;
	(void)pBitStrm;
	ret = TRUE;
	*pErrCode = 0;

	return ret  && BMSPowerStatusRequest_IsConstraintValid(pVal, pErrCode);
}


flag BMSSetHeaterDutyRequest_heater1_IsConstraintValid(const BMSSetHeaterDutyRequest_heater1* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 99UL);
    *pErrCode = ret ? 0 :  ERR_BMSSETHEATERDUTYREQUEST_HEATER1;

	return ret;
}

flag BMSSetHeaterDutyRequest_heater2_IsConstraintValid(const BMSSetHeaterDutyRequest_heater2* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 99UL);
    *pErrCode = ret ? 0 :  ERR_BMSSETHEATERDUTYREQUEST_HEATER2;

	return ret;
}

flag BMSSetHeaterDutyRequest_heater3_IsConstraintValid(const BMSSetHeaterDutyRequest_heater3* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 99UL);
    *pErrCode = ret ? 0 :  ERR_BMSSETHEATERDUTYREQUEST_HEATER3;

	return ret;
}

flag BMSSetHeaterDutyRequest_heater4_IsConstraintValid(const BMSSetHeaterDutyRequest_heater4* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 99UL);
    *pErrCode = ret ? 0 :  ERR_BMSSETHEATERDUTYREQUEST_HEATER4;

	return ret;
}

flag BMSSetHeaterDutyRequest_IsConstraintValid(const BMSSetHeaterDutyRequest* pVal, int* pErrCode)
{
    flag ret = TRUE;
    if (pVal->exist.heater1) {
    	ret = BMSSetHeaterDutyRequest_heater1_IsConstraintValid((&(pVal->heater1)), pErrCode);
    }
    if (ret) {
        if (pVal->exist.heater2) {
        	ret = BMSSetHeaterDutyRequest_heater2_IsConstraintValid((&(pVal->heater2)), pErrCode);
        }
        if (ret) {
            if (pVal->exist.heater3) {
            	ret = BMSSetHeaterDutyRequest_heater3_IsConstraintValid((&(pVal->heater3)), pErrCode);
            }
            if (ret) {
                if (pVal->exist.heater4) {
                	ret = BMSSetHeaterDutyRequest_heater4_IsConstraintValid((&(pVal->heater4)), pErrCode);
                }
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void BMSSetHeaterDutyRequest_heater1_Initialize(BMSSetHeaterDutyRequest_heater1* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void BMSSetHeaterDutyRequest_heater2_Initialize(BMSSetHeaterDutyRequest_heater2* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void BMSSetHeaterDutyRequest_heater3_Initialize(BMSSetHeaterDutyRequest_heater3* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void BMSSetHeaterDutyRequest_heater4_Initialize(BMSSetHeaterDutyRequest_heater4* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void BMSSetHeaterDutyRequest_Initialize(BMSSetHeaterDutyRequest* pVal)
{
	(void)pVal;


	/*set heater1 */
	pVal->exist.heater1 = 1;
	BMSSetHeaterDutyRequest_heater1_Initialize((&(pVal->heater1)));
	/*set heater2 */
	pVal->exist.heater2 = 1;
	BMSSetHeaterDutyRequest_heater2_Initialize((&(pVal->heater2)));
	/*set heater3 */
	pVal->exist.heater3 = 1;
	BMSSetHeaterDutyRequest_heater3_Initialize((&(pVal->heater3)));
	/*set heater4 */
	pVal->exist.heater4 = 1;
	BMSSetHeaterDutyRequest_heater4_Initialize((&(pVal->heater4)));
}

flag BMSSetHeaterDutyRequest_Encode(const BMSSetHeaterDutyRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? BMSSetHeaterDutyRequest_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,pVal->exist.heater1);
	    if (ret) {
	        BitStream_AppendBit(pBitStrm,pVal->exist.heater2);
	        if (ret) {
	            BitStream_AppendBit(pBitStrm,pVal->exist.heater3);
	            if (ret) {
	                BitStream_AppendBit(pBitStrm,pVal->exist.heater4);
	                if (ret) {
	                    /*Encode heater1 */
	                    if (pVal->exist.heater1) {
	                    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (asn1SccUint)(pVal->heater1), 0, 99);
	                    }
	                    if (ret) {
	                        /*Encode heater2 */
	                        if (pVal->exist.heater2) {
	                        	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (asn1SccUint)(pVal->heater2), 0, 99);
	                        }
	                        if (ret) {
	                            /*Encode heater3 */
	                            if (pVal->exist.heater3) {
	                            	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (asn1SccUint)(pVal->heater3), 0, 99);
	                            }
	                            if (ret) {
	                                /*Encode heater4 */
	                                if (pVal->exist.heater4) {
	                                	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (asn1SccUint)(pVal->heater4), 0, 99);
	                                }
	                            }   /*COVERAGE_IGNORE*/
	                        }   /*COVERAGE_IGNORE*/
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BMSSetHeaterDutyRequest_Decode(BMSSetHeaterDutyRequest* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	flag presenceBit;

	ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	pVal->exist.heater1 = presenceBit == 0 ? 0 : 1;
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST;
	if (ret) {
	    ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	    pVal->exist.heater2 = presenceBit == 0 ? 0 : 1;
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST;
	    if (ret) {
	        ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	        pVal->exist.heater3 = presenceBit == 0 ? 0 : 1;
	        *pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST;
	        if (ret) {
	            ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	            pVal->exist.heater4 = presenceBit == 0 ? 0 : 1;
	            *pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST;
	            if (ret) {
	                /*Decode heater1 */
	                if (pVal->exist.heater1) {
	                	ret = BitStream_DecodeConstraintPosWholeNumberUInt8(pBitStrm, (&(pVal->heater1)), 0, 99);
	                	*pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST_HEATER1;
	                }
	                if (ret) {
	                    /*Decode heater2 */
	                    if (pVal->exist.heater2) {
	                    	ret = BitStream_DecodeConstraintPosWholeNumberUInt8(pBitStrm, (&(pVal->heater2)), 0, 99);
	                    	*pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST_HEATER2;
	                    }
	                    if (ret) {
	                        /*Decode heater3 */
	                        if (pVal->exist.heater3) {
	                        	ret = BitStream_DecodeConstraintPosWholeNumberUInt8(pBitStrm, (&(pVal->heater3)), 0, 99);
	                        	*pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST_HEATER3;
	                        }
	                        if (ret) {
	                            /*Decode heater4 */
	                            if (pVal->exist.heater4) {
	                            	ret = BitStream_DecodeConstraintPosWholeNumberUInt8(pBitStrm, (&(pVal->heater4)), 0, 99);
	                            	*pErrCode = ret ? 0 : ERR_UPER_DECODE_BMSSETHEATERDUTYREQUEST_HEATER4;
	                            }
	                        }   /*COVERAGE_IGNORE*/
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && BMSSetHeaterDutyRequest_IsConstraintValid(pVal, pErrCode);
}


flag BMSSetHeaterDutyResponse_placeholder_IsConstraintValid(const BMSSetHeaterDutyResponse_placeholder* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == 0UL);
    *pErrCode = ret ? 0 :  ERR_BMSSETHEATERDUTYRESPONSE_PLACEHOLDER;

	return ret;
}

flag BMSSetHeaterDutyResponse_IsConstraintValid(const BMSSetHeaterDutyResponse* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = BMSSetHeaterDutyResponse_placeholder_IsConstraintValid((&(pVal->placeholder)), pErrCode);

	return ret;
}

void BMSSetHeaterDutyResponse_placeholder_Initialize(BMSSetHeaterDutyResponse_placeholder* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void BMSSetHeaterDutyResponse_Initialize(BMSSetHeaterDutyResponse* pVal)
{
	(void)pVal;


	/*set placeholder */
	BMSSetHeaterDutyResponse_placeholder_Initialize((&(pVal->placeholder)));
}

flag BMSSetHeaterDutyResponse_Encode(const BMSSetHeaterDutyResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? BMSSetHeaterDutyResponse_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode placeholder */
	    /* No need to encode value since it will always be 0UL */
	    (void)pBitStrm;
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BMSSetHeaterDutyResponse_Decode(BMSSetHeaterDutyResponse* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;


	/*Decode placeholder */
	pVal->placeholder=0UL;
	(void)pBitStrm;
	ret = TRUE;
	*pErrCode = 0;

	return ret  && BMSSetHeaterDutyResponse_IsConstraintValid(pVal, pErrCode);
}


flag BMSTemperatureStatusRequest_placeholder_IsConstraintValid(const BMSTemperatureStatusRequest_placeholder* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == 0UL);
    *pErrCode = ret ? 0 :  ERR_BMSTEMPERATURESTATUSREQUEST_PLACEHOLDER;

	return ret;
}

flag BMSTemperatureStatusRequest_IsConstraintValid(const BMSTemperatureStatusRequest* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = BMSTemperatureStatusRequest_placeholder_IsConstraintValid((&(pVal->placeholder)), pErrCode);

	return ret;
}

void BMSTemperatureStatusRequest_placeholder_Initialize(BMSTemperatureStatusRequest_placeholder* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void BMSTemperatureStatusRequest_Initialize(BMSTemperatureStatusRequest* pVal)
{
	(void)pVal;


	/*set placeholder */
	BMSTemperatureStatusRequest_placeholder_Initialize((&(pVal->placeholder)));
}

flag BMSTemperatureStatusRequest_Encode(const BMSTemperatureStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? BMSTemperatureStatusRequest_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode placeholder */
	    /* No need to encode value since it will always be 0UL */
	    (void)pBitStrm;
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BMSTemperatureStatusRequest_Decode(BMSTemperatureStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;


	/*Decode placeholder */
	pVal->placeholder=0UL;
	(void)pBitStrm;
	ret = TRUE;
	*pErrCode = 0;

	return ret  && BMSTemperatureStatusRequest_IsConstraintValid(pVal, pErrCode);
}


