/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"

#include "pds.h"

const asn1SccSint lfpIdPDSSystemStatusRequest = 0LL;
const asn1SccSint lfpIdPDSSystemStatusResponse = 1LL;
const asn1SccSint lfpIdPDSHealthCheckRequest = 2LL;
const asn1SccSint lfpIdPDSHealthCheckResponse = 3LL;
const asn1SccSint lfpIdPDSConverterMonitorRequest = 4LL;
const asn1SccSint lfpIdPDSConverterMonitorResponse = 5LL;
const asn1SccSint lfpIdPDSRebootRequest = 6LL;
const asn1SccSint lfpIdPDSRebootResponse = 7LL;

flag PDSADCValue_IsConstraintValid(const PDSADCValue* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 65535UL);
    *pErrCode = ret ? 0 :  ERR_PDSADCVALUE;

	return ret;
}

void PDSADCValue_Initialize(PDSADCValue* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}

flag PDSADCValue_Encode(const PDSADCValue* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? PDSADCValue_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 65535);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDSADCValue_Decode(PDSADCValue* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 65535);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_PDSADCVALUE;

	return ret  && PDSADCValue_IsConstraintValid(pVal, pErrCode);
}


flag PDSConverterMonitorResponse_IsConstraintValid(const PDSConverterMonitorResponse* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PDSADCValue_IsConstraintValid((&(pVal->int5vVs)), pErrCode);
    if (ret) {
        ret = PDSADCValue_IsConstraintValid((&(pVal->reg5vVs)), pErrCode);
        if (ret) {
            ret = PDSADCValue_IsConstraintValid((&(pVal->converterA5vVs)), pErrCode);
            if (ret) {
                ret = PDSADCValue_IsConstraintValid((&(pVal->converterB5vVs)), pErrCode);
                if (ret) {
                    ret = PDSADCValue_IsConstraintValid((&(pVal->temperatureSense)), pErrCode);
                }   /*COVERAGE_IGNORE*/
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void PDSConverterMonitorResponse_Initialize(PDSConverterMonitorResponse* pVal)
{
	(void)pVal;


	/*set int5vVs */
	PDSADCValue_Initialize((&(pVal->int5vVs)));
	/*set reg5vVs */
	PDSADCValue_Initialize((&(pVal->reg5vVs)));
	/*set converterA5vVs */
	PDSADCValue_Initialize((&(pVal->converterA5vVs)));
	/*set converterB5vVs */
	PDSADCValue_Initialize((&(pVal->converterB5vVs)));
	/*set temperatureSense */
	PDSADCValue_Initialize((&(pVal->temperatureSense)));
}

flag PDSConverterMonitorResponse_Encode(const PDSConverterMonitorResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? PDSConverterMonitorResponse_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode int5vVs */
	    ret = PDSADCValue_Encode((&(pVal->int5vVs)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode reg5vVs */
	        ret = PDSADCValue_Encode((&(pVal->reg5vVs)), pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode converterA5vVs */
	            ret = PDSADCValue_Encode((&(pVal->converterA5vVs)), pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode converterB5vVs */
	                ret = PDSADCValue_Encode((&(pVal->converterB5vVs)), pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode temperatureSense */
	                    ret = PDSADCValue_Encode((&(pVal->temperatureSense)), pBitStrm, pErrCode, FALSE);
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDSConverterMonitorResponse_Decode(PDSConverterMonitorResponse* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode int5vVs */
	ret = PDSADCValue_Decode((&(pVal->int5vVs)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode reg5vVs */
	    ret = PDSADCValue_Decode((&(pVal->reg5vVs)), pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode converterA5vVs */
	        ret = PDSADCValue_Decode((&(pVal->converterA5vVs)), pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode converterB5vVs */
	            ret = PDSADCValue_Decode((&(pVal->converterB5vVs)), pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode temperatureSense */
	                ret = PDSADCValue_Decode((&(pVal->temperatureSense)), pBitStrm, pErrCode);
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && PDSConverterMonitorResponse_IsConstraintValid(pVal, pErrCode);
}


flag PDSSystemStatusRequest_placeholder_IsConstraintValid(const PDSSystemStatusRequest_placeholder* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == 0UL);
    *pErrCode = ret ? 0 :  ERR_PDSSYSTEMSTATUSREQUEST_PLACEHOLDER;

	return ret;
}

flag PDSSystemStatusRequest_IsConstraintValid(const PDSSystemStatusRequest* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PDSSystemStatusRequest_placeholder_IsConstraintValid((&(pVal->placeholder)), pErrCode);

	return ret;
}

void PDSSystemStatusRequest_placeholder_Initialize(PDSSystemStatusRequest_placeholder* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void PDSSystemStatusRequest_Initialize(PDSSystemStatusRequest* pVal)
{
	(void)pVal;


	/*set placeholder */
	PDSSystemStatusRequest_placeholder_Initialize((&(pVal->placeholder)));
}

flag PDSSystemStatusRequest_Encode(const PDSSystemStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? PDSSystemStatusRequest_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode placeholder */
	    /* No need to encode value since it will always be 0UL */
	    (void)pBitStrm;
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDSSystemStatusRequest_Decode(PDSSystemStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;


	/*Decode placeholder */
	pVal->placeholder=0UL;
	(void)pBitStrm;
	ret = TRUE;
	*pErrCode = 0;

	return ret  && PDSSystemStatusRequest_IsConstraintValid(pVal, pErrCode);
}


flag PDSSystemStatusResponse_version_IsConstraintValid(const PDSSystemStatusResponse_version* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_PDSSYSTEMSTATUSRESPONSE_VERSION;

	return ret;
}

flag PDSSystemStatusResponse_uptime_IsConstraintValid(const PDSSystemStatusResponse_uptime* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 4294967295UL);
    *pErrCode = ret ? 0 :  ERR_PDSSYSTEMSTATUSRESPONSE_UPTIME;

	return ret;
}

flag PDSSystemStatusResponse_IsConstraintValid(const PDSSystemStatusResponse* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PDSSystemStatusResponse_version_IsConstraintValid((&(pVal->version)), pErrCode);
    if (ret) {
        ret = PDSSystemStatusResponse_uptime_IsConstraintValid((&(pVal->uptime)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void PDSSystemStatusResponse_version_Initialize(PDSSystemStatusResponse_version* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void PDSSystemStatusResponse_uptime_Initialize(PDSSystemStatusResponse_uptime* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void PDSSystemStatusResponse_Initialize(PDSSystemStatusResponse* pVal)
{
	(void)pVal;


	/*set version */
	PDSSystemStatusResponse_version_Initialize((&(pVal->version)));
	/*set uptime */
	PDSSystemStatusResponse_uptime_Initialize((&(pVal->uptime)));
}

flag PDSSystemStatusResponse_Encode(const PDSSystemStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? PDSSystemStatusResponse_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode version */
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->version, 0, 255);
	    if (ret) {
	        /*Encode uptime */
	        BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->uptime, 0, 4294967295LL);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDSSystemStatusResponse_Decode(PDSSystemStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode version */
	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->version)), 0, 255);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_PDSSYSTEMSTATUSRESPONSE_VERSION;
	if (ret) {
	    /*Decode uptime */
	    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->uptime)), 0, 4294967295LL);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_PDSSYSTEMSTATUSRESPONSE_UPTIME;
	}   /*COVERAGE_IGNORE*/

	return ret  && PDSSystemStatusResponse_IsConstraintValid(pVal, pErrCode);
}


flag PDSHealthCheckRequest_placeholder_IsConstraintValid(const PDSHealthCheckRequest_placeholder* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == 0UL);
    *pErrCode = ret ? 0 :  ERR_PDSHEALTHCHECKREQUEST_PLACEHOLDER;

	return ret;
}

flag PDSHealthCheckRequest_IsConstraintValid(const PDSHealthCheckRequest* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PDSHealthCheckRequest_placeholder_IsConstraintValid((&(pVal->placeholder)), pErrCode);

	return ret;
}

void PDSHealthCheckRequest_placeholder_Initialize(PDSHealthCheckRequest_placeholder* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void PDSHealthCheckRequest_Initialize(PDSHealthCheckRequest* pVal)
{
	(void)pVal;


	/*set placeholder */
	PDSHealthCheckRequest_placeholder_Initialize((&(pVal->placeholder)));
}

flag PDSHealthCheckRequest_Encode(const PDSHealthCheckRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? PDSHealthCheckRequest_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode placeholder */
	    /* No need to encode value since it will always be 0UL */
	    (void)pBitStrm;
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDSHealthCheckRequest_Decode(PDSHealthCheckRequest* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;


	/*Decode placeholder */
	pVal->placeholder=0UL;
	(void)pBitStrm;
	ret = TRUE;
	*pErrCode = 0;

	return ret  && PDSHealthCheckRequest_IsConstraintValid(pVal, pErrCode);
}


flag PDSHealthCheckResponse_hash_elem_IsConstraintValid(const PDSHealthCheckResponse_hash_elem* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_PDSHEALTHCHECKRESPONSE_HASH_ELM;

	return ret;
}

flag PDSHealthCheckResponse_hash_IsConstraintValid(const PDSHealthCheckResponse_hash* pVal, int* pErrCode)
{
    flag ret = TRUE;
    int i1;
    for(i1 = 0; ret && i1 < 16; i1++)
    {
    	ret = PDSHealthCheckResponse_hash_elem_IsConstraintValid((&(pVal->arr[i1])), pErrCode);
    }

	return ret;
}

flag PDSHealthCheckResponse_IsConstraintValid(const PDSHealthCheckResponse* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PDSHealthCheckResponse_hash_IsConstraintValid((&(pVal->hash)), pErrCode);

	return ret;
}

void PDSHealthCheckResponse_hash_elem_Initialize(PDSHealthCheckResponse_hash_elem* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void PDSHealthCheckResponse_hash_Initialize(PDSHealthCheckResponse_hash* pVal)
{
	(void)pVal;

    int i1;

	i1 = 0;
	while (i1< 16) {
	    PDSHealthCheckResponse_hash_elem_Initialize((&(pVal->arr[i1])));
	    i1 = i1 + 1;
	}

}
void PDSHealthCheckResponse_Initialize(PDSHealthCheckResponse* pVal)
{
	(void)pVal;


	/*set hash */
	PDSHealthCheckResponse_hash_Initialize((&(pVal->hash)));
}

flag PDSHealthCheckResponse_Encode(const PDSHealthCheckResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	int i1;
	*pErrCode = 0;
	ret = bCheckConstraints ? PDSHealthCheckResponse_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode hash */
	    for(i1=0; (i1 < (int)16) && ret; i1++)
	    {
	    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->hash.arr[i1], 0, 255);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDSHealthCheckResponse_Decode(PDSHealthCheckResponse* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	int i1;

	/*Decode hash */
	for(i1=0; (i1 < (int)16) && ret; i1++)
	{
		ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->hash.arr[i1])), 0, 255);
		*pErrCode = ret ? 0 : ERR_UPER_DECODE_PDSHEALTHCHECKRESPONSE_HASH_ELM;
	}

	return ret  && PDSHealthCheckResponse_IsConstraintValid(pVal, pErrCode);
}


flag PDSConverterMonitorRequest_placeholder_IsConstraintValid(const PDSConverterMonitorRequest_placeholder* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == 0UL);
    *pErrCode = ret ? 0 :  ERR_PDSCONVERTERMONITORREQUEST_PLACEHOLDER;

	return ret;
}

flag PDSConverterMonitorRequest_IsConstraintValid(const PDSConverterMonitorRequest* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PDSConverterMonitorRequest_placeholder_IsConstraintValid((&(pVal->placeholder)), pErrCode);

	return ret;
}

void PDSConverterMonitorRequest_placeholder_Initialize(PDSConverterMonitorRequest_placeholder* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void PDSConverterMonitorRequest_Initialize(PDSConverterMonitorRequest* pVal)
{
	(void)pVal;


	/*set placeholder */
	PDSConverterMonitorRequest_placeholder_Initialize((&(pVal->placeholder)));
}

flag PDSConverterMonitorRequest_Encode(const PDSConverterMonitorRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? PDSConverterMonitorRequest_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode placeholder */
	    /* No need to encode value since it will always be 0UL */
	    (void)pBitStrm;
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDSConverterMonitorRequest_Decode(PDSConverterMonitorRequest* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;


	/*Decode placeholder */
	pVal->placeholder=0UL;
	(void)pBitStrm;
	ret = TRUE;
	*pErrCode = 0;

	return ret  && PDSConverterMonitorRequest_IsConstraintValid(pVal, pErrCode);
}


flag PDSRebootRequest_placeholder_IsConstraintValid(const PDSRebootRequest_placeholder* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == 0UL);
    *pErrCode = ret ? 0 :  ERR_PDSREBOOTREQUEST_PLACEHOLDER;

	return ret;
}

flag PDSRebootRequest_IsConstraintValid(const PDSRebootRequest* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PDSRebootRequest_placeholder_IsConstraintValid((&(pVal->placeholder)), pErrCode);

	return ret;
}

void PDSRebootRequest_placeholder_Initialize(PDSRebootRequest_placeholder* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void PDSRebootRequest_Initialize(PDSRebootRequest* pVal)
{
	(void)pVal;


	/*set placeholder */
	PDSRebootRequest_placeholder_Initialize((&(pVal->placeholder)));
}

flag PDSRebootRequest_Encode(const PDSRebootRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? PDSRebootRequest_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode placeholder */
	    /* No need to encode value since it will always be 0UL */
	    (void)pBitStrm;
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDSRebootRequest_Decode(PDSRebootRequest* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;


	/*Decode placeholder */
	pVal->placeholder=0UL;
	(void)pBitStrm;
	ret = TRUE;
	*pErrCode = 0;

	return ret  && PDSRebootRequest_IsConstraintValid(pVal, pErrCode);
}


flag PDSRebootResponse_placeholder_IsConstraintValid(const PDSRebootResponse_placeholder* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == 0UL);
    *pErrCode = ret ? 0 :  ERR_PDSREBOOTRESPONSE_PLACEHOLDER;

	return ret;
}

flag PDSRebootResponse_IsConstraintValid(const PDSRebootResponse* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PDSRebootResponse_placeholder_IsConstraintValid((&(pVal->placeholder)), pErrCode);

	return ret;
}

void PDSRebootResponse_placeholder_Initialize(PDSRebootResponse_placeholder* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void PDSRebootResponse_Initialize(PDSRebootResponse* pVal)
{
	(void)pVal;


	/*set placeholder */
	PDSRebootResponse_placeholder_Initialize((&(pVal->placeholder)));
}

flag PDSRebootResponse_Encode(const PDSRebootResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? PDSRebootResponse_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode placeholder */
	    /* No need to encode value since it will always be 0UL */
	    (void)pBitStrm;
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDSRebootResponse_Decode(PDSRebootResponse* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;


	/*Decode placeholder */
	pVal->placeholder=0UL;
	(void)pBitStrm;
	ret = TRUE;
	*pErrCode = 0;

	return ret  && PDSRebootResponse_IsConstraintValid(pVal, pErrCode);
}


