#ifndef GENERATED_ASN1SCC_pds_H
#define GENERATED_ASN1SCC_pds_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef asn1SccUint PDSADCValue;


#define ERR_PDSADCVALUE		1  /*(0..65535)*/
flag PDSADCValue_IsConstraintValid(const PDSADCValue* pVal, int* pErrCode);

void PDSADCValue_Initialize(PDSADCValue* pVal);

#define ERR_UPER_ENCODE_PDSADCVALUE		2  /**/
#define PDSADCValue_REQUIRED_BYTES_FOR_ENCODING       2
#define PDSADCValue_REQUIRED_BITS_FOR_ENCODING        16

flag PDSADCValue_Encode(const PDSADCValue* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PDSADCVALUE		3  /**/
flag PDSADCValue_Decode(PDSADCValue* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDSConverterMonitorResponse --------------------------------------------*/
typedef struct {
    PDSADCValue int5vVs;
    PDSADCValue reg5vVs;
    PDSADCValue converterA5vVs;
    PDSADCValue converterB5vVs;
    PDSADCValue temperatureSense;

} PDSConverterMonitorResponse;

#define ERR_PDSCONVERTERMONITORRESPONSE		56  /**/
#define ERR_PDSCONVERTERMONITORRESPONSE_INT5VVS_2		11  /**/
#define ERR_PDSCONVERTERMONITORRESPONSE_REG5VVS_2		21  /**/
#define ERR_PDSCONVERTERMONITORRESPONSE_CONVERTERA5VVS_2		31  /**/
#define ERR_PDSCONVERTERMONITORRESPONSE_CONVERTERB5VVS_2		41  /**/
#define ERR_PDSCONVERTERMONITORRESPONSE_TEMPERATURESENSE_2		51  /**/
flag PDSConverterMonitorResponse_IsConstraintValid(const PDSConverterMonitorResponse* pVal, int* pErrCode);

void PDSConverterMonitorResponse_Initialize(PDSConverterMonitorResponse* pVal);

#define ERR_UPER_ENCODE_PDSCONVERTERMONITORRESPONSE		57  /**/
#define ERR_UPER_ENCODE_PDSCONVERTERMONITORRESPONSE_INT5VVS_2		12  /**/
#define ERR_UPER_ENCODE_PDSCONVERTERMONITORRESPONSE_REG5VVS_2		22  /**/
#define ERR_UPER_ENCODE_PDSCONVERTERMONITORRESPONSE_CONVERTERA5VVS_2		32  /**/
#define ERR_UPER_ENCODE_PDSCONVERTERMONITORRESPONSE_CONVERTERB5VVS_2		42  /**/
#define ERR_UPER_ENCODE_PDSCONVERTERMONITORRESPONSE_TEMPERATURESENSE_2		52  /**/
#define PDSConverterMonitorResponse_REQUIRED_BYTES_FOR_ENCODING       10
#define PDSConverterMonitorResponse_REQUIRED_BITS_FOR_ENCODING        80

flag PDSConverterMonitorResponse_Encode(const PDSConverterMonitorResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PDSCONVERTERMONITORRESPONSE		58  /**/
#define ERR_UPER_DECODE_PDSCONVERTERMONITORRESPONSE_INT5VVS_2		13  /**/
#define ERR_UPER_DECODE_PDSCONVERTERMONITORRESPONSE_REG5VVS_2		23  /**/
#define ERR_UPER_DECODE_PDSCONVERTERMONITORRESPONSE_CONVERTERA5VVS_2		33  /**/
#define ERR_UPER_DECODE_PDSCONVERTERMONITORRESPONSE_CONVERTERB5VVS_2		43  /**/
#define ERR_UPER_DECODE_PDSCONVERTERMONITORRESPONSE_TEMPERATURESENSE_2		53  /**/
flag PDSConverterMonitorResponse_Decode(PDSConverterMonitorResponse* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDSSystemStatusRequest --------------------------------------------*/
typedef asn1SccUint PDSSystemStatusRequest_placeholder;

typedef struct {
    PDSSystemStatusRequest_placeholder placeholder;

} PDSSystemStatusRequest;

#define ERR_PDSSYSTEMSTATUSREQUEST_PLACEHOLDER		61  /*(0)*/
flag PDSSystemStatusRequest_placeholder_IsConstraintValid(const PDSSystemStatusRequest_placeholder* pVal, int* pErrCode);

#define ERR_PDSSYSTEMSTATUSREQUEST		66  /**/
flag PDSSystemStatusRequest_IsConstraintValid(const PDSSystemStatusRequest* pVal, int* pErrCode);

void PDSSystemStatusRequest_placeholder_Initialize(PDSSystemStatusRequest_placeholder* pVal);
void PDSSystemStatusRequest_Initialize(PDSSystemStatusRequest* pVal);

#define ERR_UPER_ENCODE_PDSSYSTEMSTATUSREQUEST		67  /**/
#define ERR_UPER_ENCODE_PDSSYSTEMSTATUSREQUEST_PLACEHOLDER		62  /**/
#define PDSSystemStatusRequest_REQUIRED_BYTES_FOR_ENCODING       0
#define PDSSystemStatusRequest_REQUIRED_BITS_FOR_ENCODING        0

flag PDSSystemStatusRequest_Encode(const PDSSystemStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PDSSYSTEMSTATUSREQUEST		68  /**/
#define ERR_UPER_DECODE_PDSSYSTEMSTATUSREQUEST_PLACEHOLDER		63  /**/
flag PDSSystemStatusRequest_Decode(PDSSystemStatusRequest* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDSSystemStatusResponse --------------------------------------------*/
typedef asn1SccUint PDSSystemStatusResponse_version;

typedef asn1SccUint PDSSystemStatusResponse_uptime;

typedef struct {
    PDSSystemStatusResponse_version version;
    PDSSystemStatusResponse_uptime uptime;

} PDSSystemStatusResponse;

#define ERR_PDSSYSTEMSTATUSRESPONSE_VERSION		71  /*(0..255)*/
flag PDSSystemStatusResponse_version_IsConstraintValid(const PDSSystemStatusResponse_version* pVal, int* pErrCode);

#define ERR_PDSSYSTEMSTATUSRESPONSE_UPTIME		76  /*(0..4294967295)*/
flag PDSSystemStatusResponse_uptime_IsConstraintValid(const PDSSystemStatusResponse_uptime* pVal, int* pErrCode);

#define ERR_PDSSYSTEMSTATUSRESPONSE		81  /**/
flag PDSSystemStatusResponse_IsConstraintValid(const PDSSystemStatusResponse* pVal, int* pErrCode);

void PDSSystemStatusResponse_version_Initialize(PDSSystemStatusResponse_version* pVal);
void PDSSystemStatusResponse_uptime_Initialize(PDSSystemStatusResponse_uptime* pVal);
void PDSSystemStatusResponse_Initialize(PDSSystemStatusResponse* pVal);

#define ERR_UPER_ENCODE_PDSSYSTEMSTATUSRESPONSE		82  /**/
#define ERR_UPER_ENCODE_PDSSYSTEMSTATUSRESPONSE_VERSION		72  /**/
#define ERR_UPER_ENCODE_PDSSYSTEMSTATUSRESPONSE_UPTIME		77  /**/
#define PDSSystemStatusResponse_REQUIRED_BYTES_FOR_ENCODING       5
#define PDSSystemStatusResponse_REQUIRED_BITS_FOR_ENCODING        40

flag PDSSystemStatusResponse_Encode(const PDSSystemStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PDSSYSTEMSTATUSRESPONSE		83  /**/
#define ERR_UPER_DECODE_PDSSYSTEMSTATUSRESPONSE_VERSION		73  /**/
#define ERR_UPER_DECODE_PDSSYSTEMSTATUSRESPONSE_UPTIME		78  /**/
flag PDSSystemStatusResponse_Decode(PDSSystemStatusResponse* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDSHealthCheckRequest --------------------------------------------*/
typedef asn1SccUint PDSHealthCheckRequest_placeholder;

typedef struct {
    PDSHealthCheckRequest_placeholder placeholder;

} PDSHealthCheckRequest;

#define ERR_PDSHEALTHCHECKREQUEST_PLACEHOLDER		86  /*(0)*/
flag PDSHealthCheckRequest_placeholder_IsConstraintValid(const PDSHealthCheckRequest_placeholder* pVal, int* pErrCode);

#define ERR_PDSHEALTHCHECKREQUEST		91  /**/
flag PDSHealthCheckRequest_IsConstraintValid(const PDSHealthCheckRequest* pVal, int* pErrCode);

void PDSHealthCheckRequest_placeholder_Initialize(PDSHealthCheckRequest_placeholder* pVal);
void PDSHealthCheckRequest_Initialize(PDSHealthCheckRequest* pVal);

#define ERR_UPER_ENCODE_PDSHEALTHCHECKREQUEST		92  /**/
#define ERR_UPER_ENCODE_PDSHEALTHCHECKREQUEST_PLACEHOLDER		87  /**/
#define PDSHealthCheckRequest_REQUIRED_BYTES_FOR_ENCODING       0
#define PDSHealthCheckRequest_REQUIRED_BITS_FOR_ENCODING        0

flag PDSHealthCheckRequest_Encode(const PDSHealthCheckRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PDSHEALTHCHECKREQUEST		93  /**/
#define ERR_UPER_DECODE_PDSHEALTHCHECKREQUEST_PLACEHOLDER		88  /**/
flag PDSHealthCheckRequest_Decode(PDSHealthCheckRequest* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDSHealthCheckResponse --------------------------------------------*/

typedef asn1SccUint PDSHealthCheckResponse_hash_elem;


typedef struct {
    PDSHealthCheckResponse_hash_elem arr[16];
} PDSHealthCheckResponse_hash;
typedef struct {
    PDSHealthCheckResponse_hash hash;

} PDSHealthCheckResponse;

#define ERR_PDSHEALTHCHECKRESPONSE_HASH_ELM		96  /*(0..255)*/
flag PDSHealthCheckResponse_hash_elem_IsConstraintValid(const PDSHealthCheckResponse_hash_elem* pVal, int* pErrCode);

#define ERR_PDSHEALTHCHECKRESPONSE_HASH		101  /*SIZE(16)*/
flag PDSHealthCheckResponse_hash_IsConstraintValid(const PDSHealthCheckResponse_hash* pVal, int* pErrCode);

#define ERR_PDSHEALTHCHECKRESPONSE		106  /**/
flag PDSHealthCheckResponse_IsConstraintValid(const PDSHealthCheckResponse* pVal, int* pErrCode);

void PDSHealthCheckResponse_hash_elem_Initialize(PDSHealthCheckResponse_hash_elem* pVal);
void PDSHealthCheckResponse_hash_Initialize(PDSHealthCheckResponse_hash* pVal);
void PDSHealthCheckResponse_Initialize(PDSHealthCheckResponse* pVal);

#define ERR_UPER_ENCODE_PDSHEALTHCHECKRESPONSE		107  /**/
#define ERR_UPER_ENCODE_PDSHEALTHCHECKRESPONSE_HASH		102  /**/
#define ERR_UPER_ENCODE_PDSHEALTHCHECKRESPONSE_HASH_ELM		97  /**/
#define PDSHealthCheckResponse_REQUIRED_BYTES_FOR_ENCODING       16
#define PDSHealthCheckResponse_REQUIRED_BITS_FOR_ENCODING        128

flag PDSHealthCheckResponse_Encode(const PDSHealthCheckResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PDSHEALTHCHECKRESPONSE		108  /**/
#define ERR_UPER_DECODE_PDSHEALTHCHECKRESPONSE_HASH		103  /**/
#define ERR_UPER_DECODE_PDSHEALTHCHECKRESPONSE_HASH_ELM		98  /**/
flag PDSHealthCheckResponse_Decode(PDSHealthCheckResponse* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDSConverterMonitorRequest --------------------------------------------*/
typedef asn1SccUint PDSConverterMonitorRequest_placeholder;

typedef struct {
    PDSConverterMonitorRequest_placeholder placeholder;

} PDSConverterMonitorRequest;

#define ERR_PDSCONVERTERMONITORREQUEST_PLACEHOLDER		111  /*(0)*/
flag PDSConverterMonitorRequest_placeholder_IsConstraintValid(const PDSConverterMonitorRequest_placeholder* pVal, int* pErrCode);

#define ERR_PDSCONVERTERMONITORREQUEST		116  /**/
flag PDSConverterMonitorRequest_IsConstraintValid(const PDSConverterMonitorRequest* pVal, int* pErrCode);

void PDSConverterMonitorRequest_placeholder_Initialize(PDSConverterMonitorRequest_placeholder* pVal);
void PDSConverterMonitorRequest_Initialize(PDSConverterMonitorRequest* pVal);

#define ERR_UPER_ENCODE_PDSCONVERTERMONITORREQUEST		117  /**/
#define ERR_UPER_ENCODE_PDSCONVERTERMONITORREQUEST_PLACEHOLDER		112  /**/
#define PDSConverterMonitorRequest_REQUIRED_BYTES_FOR_ENCODING       0
#define PDSConverterMonitorRequest_REQUIRED_BITS_FOR_ENCODING        0

flag PDSConverterMonitorRequest_Encode(const PDSConverterMonitorRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PDSCONVERTERMONITORREQUEST		118  /**/
#define ERR_UPER_DECODE_PDSCONVERTERMONITORREQUEST_PLACEHOLDER		113  /**/
flag PDSConverterMonitorRequest_Decode(PDSConverterMonitorRequest* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDSRebootRequest --------------------------------------------*/
typedef asn1SccUint PDSRebootRequest_placeholder;

typedef struct {
    PDSRebootRequest_placeholder placeholder;

} PDSRebootRequest;

#define ERR_PDSREBOOTREQUEST_PLACEHOLDER		121  /*(0)*/
flag PDSRebootRequest_placeholder_IsConstraintValid(const PDSRebootRequest_placeholder* pVal, int* pErrCode);

#define ERR_PDSREBOOTREQUEST		126  /**/
flag PDSRebootRequest_IsConstraintValid(const PDSRebootRequest* pVal, int* pErrCode);

void PDSRebootRequest_placeholder_Initialize(PDSRebootRequest_placeholder* pVal);
void PDSRebootRequest_Initialize(PDSRebootRequest* pVal);

#define ERR_UPER_ENCODE_PDSREBOOTREQUEST		127  /**/
#define ERR_UPER_ENCODE_PDSREBOOTREQUEST_PLACEHOLDER		122  /**/
#define PDSRebootRequest_REQUIRED_BYTES_FOR_ENCODING       0
#define PDSRebootRequest_REQUIRED_BITS_FOR_ENCODING        0

flag PDSRebootRequest_Encode(const PDSRebootRequest* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PDSREBOOTREQUEST		128  /**/
#define ERR_UPER_DECODE_PDSREBOOTREQUEST_PLACEHOLDER		123  /**/
flag PDSRebootRequest_Decode(PDSRebootRequest* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDSRebootResponse --------------------------------------------*/
typedef asn1SccUint PDSRebootResponse_placeholder;

typedef struct {
    PDSRebootResponse_placeholder placeholder;

} PDSRebootResponse;

#define ERR_PDSREBOOTRESPONSE_PLACEHOLDER		131  /*(0)*/
flag PDSRebootResponse_placeholder_IsConstraintValid(const PDSRebootResponse_placeholder* pVal, int* pErrCode);

#define ERR_PDSREBOOTRESPONSE		136  /**/
flag PDSRebootResponse_IsConstraintValid(const PDSRebootResponse* pVal, int* pErrCode);

void PDSRebootResponse_placeholder_Initialize(PDSRebootResponse_placeholder* pVal);
void PDSRebootResponse_Initialize(PDSRebootResponse* pVal);

#define ERR_UPER_ENCODE_PDSREBOOTRESPONSE		137  /**/
#define ERR_UPER_ENCODE_PDSREBOOTRESPONSE_PLACEHOLDER		132  /**/
#define PDSRebootResponse_REQUIRED_BYTES_FOR_ENCODING       0
#define PDSRebootResponse_REQUIRED_BITS_FOR_ENCODING        0

flag PDSRebootResponse_Encode(const PDSRebootResponse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PDSREBOOTRESPONSE		138  /**/
#define ERR_UPER_DECODE_PDSREBOOTRESPONSE_PLACEHOLDER		133  /**/
flag PDSRebootResponse_Decode(PDSRebootResponse* pVal, BitStream* pBitStrm, int* pErrCode);

extern const asn1SccSint lfpIdPDSSystemStatusRequest;
extern const asn1SccSint lfpIdPDSSystemStatusResponse;
extern const asn1SccSint lfpIdPDSHealthCheckRequest;
extern const asn1SccSint lfpIdPDSHealthCheckResponse;
extern const asn1SccSint lfpIdPDSConverterMonitorRequest;
extern const asn1SccSint lfpIdPDSConverterMonitorResponse;
extern const asn1SccSint lfpIdPDSRebootRequest;
extern const asn1SccSint lfpIdPDSRebootResponse;

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
