CONFIG_SPI=y
CONFIG_CACHE_MANAGEMENT=y
CONFIG_BUILD_OUTPUT_HEX=y
# CONFIG_INIT_STACKS is not set
CONFIG_HW_STACK_PROTECTION=y
CONFIG_WDT_DISABLE_AT_BOOT=y
CONFIG_LOG=y
CONFIG_CONSOLE=y
CONFIG_ULOG=y
CONFIG_ULOG_LOG_BACKEND=y
CONFIG_ARM_MPU=y
# CONFIG_DEVICE_DT_METADATA is not set
CONFIG_UART_CONSOLE=y
CONFIG_I2C=y
CONFIG_I2C_SHELL=y
CONFIG_LED=y
CONFIG_UART_SHELL=y
CONFIG_SPI_SHELL=y
# CONFIG_LOG_RUNTIME_FILTERING is not set
# CONFIG_LOG_BACKEND_SHOW_COLOR is not set
CONFIG_SHELL=y
